### ISSUE TITLE
Cannot create nested environments

### ISSUE THREAD

**Issue by wr0ngway** [cloudtruth/terraform-provider-cloudtruth#8]
Created on behalf of @EugeneAikashev

It seems very difficult to create a nested environment like level1->level2->level3 in one terraform run. I have to apply the code 3 times ( ...
Here is my simple code:
```
resource "cloudtruth_project" "test" {
  name        = "test"
  description = "This is a Test project created by Terraform"
  force_delete = true
}

resource "cloudtruth_environment" "level1" {
  name         = "level1"
  description  = "Level1 created by Terraform"
  parent       = "default"
  force_delete = true
}

resource "cloudtruth_environment" "level2" {
  name         = "level2"
  description  = "Level2 created by Terraform"
  parent       = "level1"
  force_delete = true
}

resource "cloudtruth_environment" "level3" {
  name         = "level3"
  description  = "Level3 created by Terraform"
  parent       = "level2"
  force_delete = true
}
```
First apply:
```
cloudtruth_project.test: Creating...
cloudtruth_environment.level3: Creating...
cloudtruth_environment.level2: Creating...
cloudtruth_environment.level1: Creating...
cloudtruth_environment.level1: Creation complete after 1s [id=29f5fb95-30e2-4a73-ada9-09f1393f312f]
cloudtruth_project.test: Creation complete after 1s [id=d5755c2f-6c37-4f6c-a98e-4bcd3be039f2]

│ Error: resourceEnvironmentCreate: lookupEnvironment: environment with name/ID level1 not found
│ Error: resourceEnvironmentCreate: lookupEnvironment: environment with name/ID level2 not found
```
Second apply:
```
cloudtruth_environment.level2: Creating...
cloudtruth_environment.level3: Creating...
cloudtruth_environment.level2: Creation complete after 1s [id=297ce6cb-a3ae-435e-95a6-ad0243dbc6f8]
╷
│ Error: resourceEnvironmentCreate: lookupEnvironment: environment with name/ID level2 not found
Third apply -
cloudtruth_environment.level3: Creating...
cloudtruth_environment.level3: Creation complete after 1s [id=c3ef5044-2815-49c1-8c29-c17b0ff6e4ca]
```

**Comment by matthewcummings** [comment]
@EugeneAikashev thank you for find and logging this issue. It is fixed in `v0.3.0`. One other thing to note, in order to guarantee that Terraform creates the environments in the correct order, you should the resource property syntax to specify the names of the parent environments e.g.

`resource "cloudtruth_project" "test" {
  name        = "test"
  description = "This is a Test project created by Terraform"
  force_delete = true
}

resource "cloudtruth_environment" "level1" {
  name         = "level1"
  description  = "Level1 created by Terraform"
  parent       = "default"
  force_delete = true
}

resource "cloudtruth_environment" "level2" {
  name         = "level2"
  description  = "Level2 created by Terraform"
  parent       = "level1"
  force_delete = true
}

resource "cloudtruth_environment" "level3" {
  name         = "level3"
  description  = "Level3 created by Terraform"
  parent       = "level2"
  force_delete = true
}`

**Comment by matthewcummings** [comment]
@EugeneAikashev please let me know if you see any further issues with this functionality or the provider in general. Cheers.

**Comment by matthewcummings** [comment]
@EugeneAikashev I'm closing this ticket now. Please reopen it if you see further issues or create a new one.
